name: Pipeline
on: [pull_request]

jobs:
  CI:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Quality checks
        run: make quality

      - name: Build and test plugin
        run: make e2e
