name: Basic pipeline
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show code
        run: ls -R $GITHUB_WORKSPACE/