name: Basic pipeline
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Format code
        run: make format

      - name: Build and test plugin
        run: make e2e